export const ServerVariables = {
  Landing: "/",



  //userRoutes
  Login: "/login",
  Register: "/signup",
  Otp:'/otp',
  VerifyEmail: '/verify-email',
  changePassword : '/change-password',
  UserHome:'/UserHome',
  postDetails:'/postDetails',
  userProfile:'/userProfile',
  editUser:'/editUser',
  addJobProfile:'/addJobProfile',
  editJobProfile:'/editJobProfile',
  showEvent:'/showEvent', 
  chatPage:'/chats',
  userVideoCallRoom:'/userRoom',
  explore:'/explore',
  searchEvent:'/searchEvent',
  userNotifications:'/userNotifications',
  jobDetails:'/jobDetails',
  jobStats:'/jobStats',
  showJobs:'/showJobs',
  
  //admin routes
  AdminLogin:'/adminLogin',
  AdminHome:'/adminHome',
  UsersTable:'/users',
  PlansTable:'/plansTable',
  AddPlan:'/AddPlan',
  editPlan:'/editPlan',
  eventsTable:'/events',
  BannersTable:'/banners',
  addBanner:'/addBanner',
  editBanner:'/editBanner',


  //event routes
  eventLogin : '/eventLogin',
  eventRegister: '/eventRegister',
  eventOtp:'/eventOtp',
  eventEmailVerification: '/eventEmailVerification',
  changeEventPassword : '/changeEventPassword',
  eventHome:'/eventHome',
  editEvent:'/editEvent',
  editProfileImage:'/editProfileImage',
  addPost:'/addPost',
  addStory:'/addStory',
  storyCourosel:'/storyCourosel',
  PlansAvailable:'/Plans',
  success:'/PaymentSuccess',
  error:'/PaymentError',
  eventChats:'/eventChats',
  eventNotifications:'/eventNotifications',
  EventVideoCallRoom:'/EventRoom',
  hirings:'/hirings',
  postJob:'/postJob',
  editJobPost:'/editJobPost',
  showUser:'/showUser',
  eventJobStats:'/eventJobStats',
};

